server:
  port: 8088
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: false

